# development:
#   adapter: postgresql
#   encoding: unicode
#   database: demo_test_development
#   pool: 5
#   timeout: 5000
#
#
#   test:
#   adapter: postgresql
#   encoding: unicode
#   database: demo_test_test
#   pool: 5
#   timeout: 5000


development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
